name: Claude Assistant- Issue Review

on:
  issues:
    types: [labeled]

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  claude-response:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 전체 히스토리 클론 (0으로 설정)

      - name: Run Claude Code Action
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          label_trigger: "claude-review"
          custom_instructions: |
            당신은 한국어 코드 리뷰어입니다. 반드시 한국어로만 응답해야 합니다.
            이슈와 관련하여 다음 항목을 구조적으로 간략하게 정리해 주세요. 
            
            1. 기능 목적: 이 기능이 필요한 이유와 기대 효과를 간략하게 설명해 주세요.
            2. 영향 범위: 개발 시 영향을 받는 주요 컴포넌트, 모듈, 또는 시스템 범위를 구체적으로 나열해 주세요. 읽기 쉽게 표나 목록으로 정리해 주세요.
            3. 구현 전략: 실제 개발을 위한 단계별 구현 방안 및 전략을 제시해 주세요. 읽기 쉽게 표나 목록으로 정리해 주세요.
